import time
import close
import os

def start():
 os.system("cls")
 print("Note: this actions take some minutes, for some users can take 1 hours, just wait!")
 print("Running SFC /SCANNOW")
 os.system("sfc /scannow")
 os.system("cls")
 print("Running SFC /SCANNOW (DONE)")
 print("Clearing Temp Files")
 os.system("del /q/f/s %TEMP%\*")
 os.system("del /q/f/s C:\Windows\temp\*")
 os.system("del /q/f/s C:\Windows\Prefetch\*")
 os.system("cls")
 print("Running SFC /SCANNOW (DONE)")
 print("Clearing Temp Files (DONE)")
 print("Running chkdsk/r")
 os.system("chkdsk/r")
 os.system("cls")
 print("Running SFC /SCANNOW (DONE)")
 print("Clearing Temp Files (DONE)")
 print("Running chkdsk/r (DONE)")
 time.sleep(3)
 os.system("cls")
 print()
 print()
 print("Finishing, Just wait (Clearing caches)")
 os.system("del /q/f/s %TEMP%\*")
 os.system("del /q/f/s C:\Windows\temp\*")
 os.system("del /q/f/s C:\Windows\Prefetch\*")
 time.sleep(10)
 os.system("cls")
 print("Finished, Just Close window")
 os.system("pause")
 close()